{% set name = "sympytensor" %}
{% set version = "1.4.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sympytensor-{{ version }}.tar.gz
  sha256: 25e69141de40fe770210ff65513c7a0aab1e614af8b20f8c610f2add1e82a01a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - pytensor >=2.37.0
    - sympy
    - pymc
    - mpmath >=1.1.0,<1.4.0

test:
  imports:
    - sympytensor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jessegrabowski/sympytensor
  summary: Print sympy expressions to pytensor graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessegrabowski
