{% set name = "sympytensor" %}
{% set version = "1.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sympytensor-{{ version }}.tar.gz
  sha256: 0ff96191927dbe80e518cbb07c8aa108bac7903691bf67feb535f3d352c49362

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - pytensor
    - sympy
    - pymc

test:
  imports:
    - sympytensor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jessegrabowski/sympytensor
  summary: Print sympy expressions to pytensor graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessegrabowski
